const assert = require('assert')
const fs = require('fs')

const source = fs.readFileSync('cloudfunctions/get-ranking/index.js', 'utf8')
const service = fs.readFileSync('miniprogram/services/ranking.js', 'utf8')
const page = fs.readFileSync('miniprogram/pages/student/rank/rank.js', 'utf8')
const view = fs.readFileSync('miniprogram/pages/student/rank/rank.wxml', 'utf8')
const reviews = fs.readFileSync('miniprogram/pages/teacher/pending/pending.js', 'utf8')

assert.match(source, /current_user_only/)
assert.match(source, /page_size/)
assert.match(source, /has_more/)
assert.match(source, /markedList\.slice\(start, start \+ pageSize\)/)
assert.match(service, /current_user_only:\s*true/)
assert.match(page, /RANKING_PAGE_SIZE\s*=\s*30/)
assert.match(page, /onScrollToLower/)
assert.match(page, /displayRanks\.concat/)
assert.match(view, /bindscrolltolower="onScrollToLower"/)
assert.match(reviews, /REVIEW_RENDER_LIMIT\s*=\s*200/)
assert.match(reviews, /slice\(0, remaining\)/)
